### ISSUE TITLE
Forking and Licensing

### ISSUE THREAD

**Issue by yeojz** [richardstevens/metalsmith-react-tpl#3]
Hi @richardstevens 

Just noticed this repo. If this is a fork, I'll much appreciate if you maintain the appropriate licensing and credits. Thank You.

On that note, if you can help with the original repo, it would be great!

**Comment by yangshun** [comment]
:+1:

**Comment by richardstevens** [comment]
Thanks for your comment, i have included a license mention in the Readme for this repo to tie back to yours as a thank you for the initial fork
